### PR TITLE
made the default constructors private where relevant, for the Node types

### PR DESCRIPTION
**Pull request by ofloveandhate**
This resolves the problem with creating empty nodes in a tree, which should be not allowed.  Now it isn't!

### CODE REVIEW

**Comment by ofloveandhate** [comment]
i vote for the immediate acceptance of this pull request.  creating empty nodes is nonsense, and this pull request addresses that problem.

the only downside of this PR is that people who currently depend on making empty nodes will have to modify their code to not do that any more, an acceptable side-effect.  they shouldn't do it anyway!

any opposed?

**Comment by jbcolli2** [comment]
Fine by me, I've already changed the python code to not include empty
constructors.

  Jeb

On Wed, Mar 2, 2016 at 10:30 AM, daniel brake <notifications@github.com>
wrote:

> i vote for the immediate acceptance of this pull request. creating empty
> nodes is nonsense, and this pull request addresses that problem.
>
> the only downside of this PR is that people who currently depend on making
> empty nodes will have to modify their code to not do that any more, an
> acceptable side-effect. they shouldn't do it anyway!
>
> any opposed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bertiniteam/b2/pull/23#issuecomment-191314737>.
>



-- 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by timothodge** [comment]
Never constructed empty nodes, so I say go for it!

Tim

On Wed, Mar 2, 2016 at 9:55 AM, Jeb Collins <notifications@github.com>
wrote:

> Fine by me, I've already changed the python code to not include empty
> constructors.
>
> Jeb
>
> On Wed, Mar 2, 2016 at 10:30 AM, daniel brake <notifications@github.com>
> wrote:
>
> > i vote for the immediate acceptance of this pull request. creating empty
> > nodes is nonsense, and this pull request addresses that problem.
> >
> > the only downside of this PR is that people who currently depend on
> making
> > empty nodes will have to modify their code to not do that any more, an
> > acceptable side-effect. they shouldn't do it anyway!
> >
> > any opposed?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bertiniteam/b2/pull/23#issuecomment-191314737>.
> >
>
>
>
> --
>
> J.B. Collins, Ph.D
> West Texas A&M University
> Department of Mathematics
> CC 421D
> 806-651-5260
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bertiniteam/b2/pull/23#issuecomment-191323984>.
>



-- 
Tim Hodges
Colorado State University
Department of Mathematics

**Comment by dbates1** [comment]
Never constructed nodes, let alone empty ones.  Seems fine to me.

**Comment by bertiniteam** [comment]
accepted

**Pull request merged**
