### PR TITLE
start system, function tree, classic parser

### PR DESCRIPTION
**Pull request by ofloveandhate**
I am filing this pull request to get the latest coded features into the main dev branch.  This includes

* a fully functional parser for bertini classic input (not including the config portion).
* the basics for the total degree start system
* methods for homogenization, degree computations, checks for polynomiality,
* a full multiprecision evaluation tree,
* doxygen comments for all classes,
* rational, float, and integer classes,
* and many other features.

i probably waited too long before issuing this, but here it is.  i will try to do these more frequently in the future.  

any and all feedback is welcome, including code review.

### CODE REVIEW

**Comment by fpancald** [comment]
#14 configuration issue @ofloveandhate @bertiniteam @fpancald
- 
g++ -DHAVE_CONFIG_H -I.  -I./include -I/afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/include -I/afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/mpfr/3.1.3/include/ -I/afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/gmp/6.0.0/include/ -I/afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/boost/1.58.0/include -g -O2 -std=gnu++14 -MT src/function_tree/bertini2-node.o -MD -MP -MF src/function_tree/.deps/bertini2-node.Tpo -c -o src/function_tree/bertini2-node.o `test -f 'src/function_tree/node.cpp' || echo './'`src/function_tree/node.cpp
In file included from ./include/mpfr_complex.hpp:31:0,
                 from ./include/function_tree/node.hpp:35,
                 from ./include/function_tree.hpp:29,
                 from src/function_tree/node.cpp:1:
./include/mpfr_extensions.hpp: In function ‘void boost::serialization::save(Archive&, const boost::multiprecision::backends::mpfr_float_backend<0u, (boost::multiprecision::mpfr_allocation_type)1u>&, unsigned int)’:
./include/mpfr_extensions.hpp:58:33: error: no matching function for call to ‘boost::multiprecision::backends::mpfr_float_backend<0u, (boost::multiprecision::mpfr_allocation_type)1u>::str(int, bool) const’
   std::string tmp = r.str(0,true);
                                 ^
./include/mpfr_extensions.hpp:58:33: note: candidate is:
In file included from ./include/mpfr_extensions.hpp:29:0,
                 from ./include/mpfr_complex.hpp:31,
                 from ./include/function_tree/node.hpp:35,
                 from ./include/function_tree.hpp:29,
                 from src/function_tree/node.cpp:1:
/afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/boost/1.58.0/include/boost/multiprecision/mpfr.hpp:198:16: note: std::string boost::multiprecision::backends::detail::mpfr_float_imp<digits10, (boost::multiprecision::mpfr_allocation_type)1u>::str(std::streamsize, std::ios_base::fmtflags) const [with unsigned int digits10 = 0u; std::string = std::basic_string<char>; std::streamsize = long int; std::ios_base::fmtflags = std::_Ios_Fmtflags]
    std::string str(std::streamsize digits, std::ios_base::fmtflags f)const
                ^
/afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/boost/1.58.0/include/boost/multiprecision/mpfr.hpp:198:16: note:   no known conversion for argument 2 from ‘bool’ to ‘std::ios_base::fmtflags {aka std::_Ios_Fmtflags}’
In file included from ./include/mpfr_complex.hpp:31:0,
                 from ./include/function_tree/node.hpp:35,
                 from ./include/function_tree.hpp:29,
                 from src/function_tree/node.cpp:1:
./include/mpfr_extensions.hpp: In function ‘void boost::serialization::save(Archive&, const boost::multiprecision::backends::gmp_rational&, unsigned int)’:
./include/mpfr_extensions.hpp:80:33: error: no matching function for call to ‘boost::multiprecision::backends::gmp_rational::str(int, bool) const’
   std::string tmp = r.str(0,true);
                                 ^
./include/mpfr_extensions.hpp:80:33: note: candidate is:
In file included from /afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/boost/1.58.0/include/boost/multiprecision/mpfr.hpp:10:0,
                 from ./include/mpfr_extensions.hpp:29,
                 from ./include/mpfr_complex.hpp:31,
                 from ./include/function_tree/node.hpp:35,
                 from ./include/function_tree.hpp:29,
                 from src/function_tree/node.cpp:1:
/afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/boost/1.58.0/include/boost/multiprecision/gmp.hpp:1896:16: note: std::string boost::multiprecision::backends::gmp_rational::str(std::streamsize, std::ios_base::fmtflags) const
    std::string str(std::streamsize /*digits*/, std::ios_base::fmtflags /*f*/)const
                ^
/afs/crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/boost/1.58.0/include/boost/multiprecision/gmp.hpp:1896:16: note:   no known conversion for argument 2 from ‘bool’ to ‘std::ios_base::fmtflags {aka std::_Ios_Fmtflags}’

**Comment by ofloveandhate** [comment]
Francesco,
I have fixed these problems, and can now compile without warning on the CRC's machine.  

Several tests fail, and I am working on understanding the reason for these failures.  The are on function residuals for TotalDegree start systems, evaluated at start points.  A few points are such that the residual is *just larger* than the threshold for success.  Is this because of the way I constructed the start point, or is the residual tolerance unreasonable?  That's what I am working on.  

But at least you can compile it on CRC now.  

Alan, and any other gcc users, I expect you will also be able to compile now.  Please let me know if that is not the case.  Note that you will have to pull from my repo to get the changes.

**Comment by ofloveandhate** [comment]
I have fixed the failing tests under gcc -- namely the complex test, and the test on TotalDegree start system function residuals.  Everyone should pull and re-test.

**Comment by aliddell** [comment]
Running `make b2_class_test` gets me 

In file included from src/bertini/limbo.cpp:1:0:
./include/limbo.hpp: In function ‘std::vector<T> bertini::IndexToSubscript(T, const std::vector<T>&)’:
./include/limbo.hpp:55:11: error: ‘out_of_range’ is not a member of ‘std’
     throw std::out_of_range("in IndexToSubscript, index exceeds max based on dimension sizes");
           ^
Makefile:1106: recipe for target 'src/bertini/b2_class_test-limbo.o' failed
make: *** [src/bertini/b2_class_test-limbo.o] Error 1

**Comment by fpancald** [comment]
malthael:~/bertinitest/b2/core> make
make  all-am
make[1]: Entering directory `/afs/
crc.nd.edu/user/f/fpancald/bertinitest/b2/core'
g++ -DHAVE_CONFIG_H -I.  -I./include -I/afs/
crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/include -I/afs/
crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/mpfr/3.1.3/include/ -I/afs/
crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/gmp/6.0.0/include/ -I/afs/
crc.nd.edu/user/f/fpancald/Private/code/ -I/afs/
crc.nd.edu/x86_64_linux/b/bertini/1.5/gcc/4.9.2/boost/1.58.0/include -g -O2
-std=gnu++14 -MT src/bertini/bertini2-limbo.o -MD -MP -MF
src/bertini/.deps/bertini2-limbo.Tpo -c -o src/bertini/bertini2-limbo.o
`test -f 'src/bertini/limbo.cpp' || echo './'`src/bertini/limbo.cpp
In file included from src/bertini/limbo.cpp:1:0:
./include/limbo.hpp: In function ‘std::vector<T>
bertini::IndexToSubscript(T, const std::vector<T>&)’:
./include/limbo.hpp:55:11: error: ‘out_of_range’ is not a member of ‘std’
     throw std::out_of_range("in IndexToSubscript, index exceeds max based
on dimension sizes");
           ^
make[1]: *** [src/bertini/bertini2-limbo.o] Error 1
make[1]: Leaving directory `/afs/
crc.nd.edu/user/f/fpancald/bertinitest/b2/core'
make: *** [all] Error 2

**Comment by ofloveandhate** [comment]
I believe it is fixed.  please try again.

**Comment by aliddell** [comment]
Can confirm that it compiles now on Fedora 22 with GCC 5.1.1 and Boost 1.57.

**Comment by ofloveandhate** [comment]
can you successfully run b2_class_test?  it's not build by default, is a separate make target.

**Comment by aliddell** [comment]
No errors detected.

**Comment by fpancald** [comment]
Can confirm that it compiles on the crc (both 'make' and 'make
b2_class_test')
Only remaining problem on the ACMS front node when running tests, but
talking with Daniel we think this is most probably due to a gmp library
issue on the specific node, because the test run fine on any other node we
tried.

crc Front Node          Test passed

acms.crc.nd.edu        NO
fermife.crc.nd.edu      YES
bertini1.crc.nd.edu     YES
crcfe01.crc.nd.edu     YES
crcfe02.crc.nd.edu     YES
crcfeIB01.crc.nd.edu  YES
gpu1.crc.nd.edu         YES
gpu2.crc.nd.edu         YES
gpu3.crc.nd.edu         YES
gpu4.crc.nd.edu         YES
gpu5.crc.nd.edu         YES
gpu6.crc.nd.edu         YES
digitaltoast.crc.nd.edu YES
heartofgold.crc.nd.edu YES
daccssfe.crc.nd.edu    YES

I may try some more Front Nodes later on, but it really appears to be a
specific problem just with the ACMS one.

**Comment by ofloveandhate** [comment]
What remains for this pull request?  Do we need more test coverage?  If not, then can we do the pull?

**Comment by fpancald** [comment]
I will try to go through all the tests today.
I think also Tim was going to look at it, right?
Once I have finished looking at this I will compile my report and submit it
to Dan asking for the approval of the pull request.

Best

Francesco

**Comment by bertiniteam** [comment]
That sounds good (except that Jeb is the other reviewer for this pull
request, not Tim).

Thanks,
Dan

**Comment by jbcolli2** [comment]
The only addition I can think of is a test in start_system trying to create
a start system from a non polynomial.

On Fri, Sep 4, 2015 at 8:37 AM, daniel brake <notifications@github.com>
wrote:

> What remains for this pull request? Do we need more test coverage? If not,
> then can we do the pull?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bertiniteam/b2/pull/8#issuecomment-137739991>.
>



-- 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by ofloveandhate** [comment]
Thanks, Jeb.  I will add a few tests regarding the construction of
TotalDegree start system from non-polynomial systems, which should fail
(not the test, but the construction).

daniel

**Comment by fpancald** [comment]
Here are my suggestions for the test files.
After receiving a reply about these I will consider myself satisfied regarding the tests. 
On Monday I will take a second look at the rest of the code and compile my review report to send to Dan.
@ofloveandhate let me know if something is not clear

File | Issue/Suggestion 
-----|-------------------------------
function_tree_test.cpp| 1. in ``` BOOST_AUTO_TEST_CASE(manual_construction_x_squared) ``` and ``` BOOST_AUTO_TEST_CASE(manual_construction_sqrt_x) ``` should change ```x->set_current_value<dbl>(std::complex<double>(3.1, 4.1)); ``` to ``` x->set_current_value<dbl>(xnum_dbl); ``` as is in ``` BOOST_AUTO_TEST_CASE(manual_construction_x_plus_y_plus_number) ```
 | 2. ```BOOST_AUTO_TEST_CASE(manual_construction_x_minus_y_minus_number)``` could add more permutations of operation as is in ```BOOST_AUTO_TEST_CASE(manual_construction_x_plus_y_plus_number)```
 | 3. missing  ```BOOST_CHECK_EQUAL(N->Degree(),-1);``` after ```std::shared_ptr<Node> N = x/y;``` in ```BOOST_AUTO_TEST_CASE(manual_construction_x_divide_y)```
 | 4. missing ```BOOST_CHECK(! N->IsPolynomial());``` for y/x in ```BOOST_AUTO_TEST_CASE(manual_construction_x_divide_y)```
 | 5. could add operation permutations to ```BOOST_AUTO_TEST_CASE(manual_construction_x_times_y_over_num)``` as follow
```
    N = (x*y)/a;
    BOOST_CHECK_EQUAL(N->Degree(),2);
    BOOST_CHECK_EQUAL(N->Degree(x),1);
    BOOST_CHECK_EQUAL(N->Degree(y),1);

    BOOST_CHECK(fabs(N->Eval<dbl>().real() - exact_dbl.real() ) < threshold_clearance_d);
    BOOST_CHECK(fabs(N->Eval<dbl>().imag() - exact_dbl.imag() ) < threshold_clearance_d);
    BOOST_CHECK(fabs(N->Eval<mpfr>().real() - exact_mpfr.real() ) < threshold_clearance_mp);
    BOOST_CHECK(fabs(N->Eval<mpfr>().imag() - exact_mpfr.imag() ) < threshold_clearance_mp);

    N = x/a*y;
    BOOST_CHECK_EQUAL(N->Degree(),2);
    BOOST_CHECK_EQUAL(N->Degree(x),1);
    BOOST_CHECK_EQUAL(N->Degree(y),1);

    BOOST_CHECK(fabs(N->Eval<dbl>().real() - exact_dbl.real() ) < threshold_clearance_d);
    BOOST_CHECK(fabs(N->Eval<dbl>().imag() - exact_dbl.imag() ) < threshold_clearance_d);
    BOOST_CHECK(fabs(N->Eval<mpfr>().real() - exact_mpfr.real() ) < threshold_clearance_mp);
    BOOST_CHECK(fabs(N->Eval<mpfr>().imag() - exact_mpfr.imag() ) < threshold_clearance_mp);
```
File | Issue/Suggestion 
-----|-------------------------------
function_tree_test.cpp | 6. substitute  ```std::shared_ptr<Float> b = std::make_shared<Float>("-0.2", "-2.1");``` with ```std::shared_ptr<Float> b = std::make_shared<Float>(bstr_real, bstr_imag);``` in ```BOOST_AUTO_TEST_CASE(manual_construction_lx_plus_num1l_times_ly_plus_num2l)```, ```BOOST_AUTO_TEST_CASE(manual_construction_x_plus_num1_times_y_plus_num2)``` , ```BOOST_AUTO_TEST_CASE(manual_construction_lx_plus_num1l_over_ly_plus_num2l)```, and ```BOOST_AUTO_TEST_CASE(manual_construction_x_plus_num1_over_y_plus_num2)```
 | 7. may want to add to ```BOOST_AUTO_TEST_CASE(manual_construction_sqrt_of_lx_pow_numl)``` the following
    exact_dbl = pow(sqrt(xnum_dbl),anum_dbl);
    exact_mpfr = pow(sqrt(xnum_mpfr),anum_mpfr);

    N = pow(sqrt(x),a);
    BOOST_CHECK_EQUAL(N->Degree(),-1);
    BOOST_CHECK_EQUAL(N->Degree(x),-1);

    BOOST_CHECK(fabs(N->Eval<dbl>().real() - exact_dbl.real() ) < threshold_clearance_d);
    BOOST_CHECK(fabs(N->Eval<dbl>().imag() - exact_dbl.imag() ) < threshold_clearance_d);
    BOOST_CHECK(fabs(N->Eval<mpfr>().real() - exact_mpfr.real() ) < threshold_clearance_mp);
    BOOST_CHECK(fabs(N->Eval<mpfr>().imag() - exact_mpfr.imag() ) < threshold_clearance_mp);

    N = pow(x,1/2.0);
    BOOST_CHECK_EQUAL(N->Degree(),-1);
    BOOST_CHECK_EQUAL(N->Degree(x),-1);
    N = pow(N,a);
    BOOST_CHECK_EQUAL(N->Degree(),-1);
    BOOST_CHECK_EQUAL(N->Degree(x),-1);

    BOOST_CHECK(fabs(N->Eval<dbl>().real() / exact_dbl.real() -1) < threshold_clearance_d);
    BOOST_CHECK(fabs(N->Eval<dbl>().imag() - exact_dbl.imag() ) < threshold_clearance_d);
    BOOST_CHECK(fabs(N->Eval<mpfr>().real() - exact_mpfr.real() ) < threshold_clearance_mp);
    BOOST_CHECK(fabs(N->Eval<mpfr>().imag() - exact_mpfr.imag() ) < threshold_clearance_mp);
File | Issue/Suggestion 
-----|-------------------------------
function_tree_test.cpp | 8. Do we have an integer (positive or not) powers operation? like pow(x,5) giving x^5 as polynomial of degree 5?or such that pow(x,3)*pow(x,-1)=x^2?
 | 9. add ```BOOST_CHECK(!N->IsPolynomial());``` to ```BOOST_AUTO_TEST_CASE(arcsine_evaluate)``` , ```BOOST_AUTO_TEST_CASE(arccosine_evaluate)```, and ```BOOST_AUTO_TEST_CASE(arctangent_evaluate)```
 | 10. should add one or two tests for logarithm 
differentiate_test.cpp | 1.should add a test to differentiate logarithm
 | 2.  there are a bunch of commented out tests at the end. If they are not there for a specific reason they should be removed.
 node_serialization.cpp | 1. should the name  of this file be changed to node_serialization_test.cpp?
function_tree_interactive.cpp  | 1. is this used in the actual test suite? will it be there in the future? is just for development purpose?

**Comment by ofloveandhate** [comment]
@fpancald , these are great suggestions.  I have made changes but not yet propagated them, regarding items 1-7.

Number 8 does not yet work, I have to do some dynamic type conversions inside the division operator.

I'm working on the rest of the changes, too.

**Comment by ofloveandhate** [comment]
@jbcolli2, i added the non-polynomial TD start system test, as you requested.  not propagated yet, but will merge into my repo after i finish the rest of francesco's requests.

**Comment by fpancald** [comment]
Here are my suggestions for the rest of the code.
I have been through all the code (*.cpp and *.hpp). I will now compile my report on the pull request and will send it to Dan as soon as I receive a final response regarding these (and the previous suggestions).
@ofloveandhate let me know if something is not clear

File | Issue/Suggestion 
-----|-------------------------------
arithmetic.cpp | 1. may want to have tests for ```int PowerOperator::Degree(std::shared_ptr<Variable> const& v) const``` like check that ```degree(pow(x^2,2))=4```, etc...
 | 2. for the square root operator may want to add a check for the case in which the degree of the child is a positive even integer. For example if we are doing ```sqrt(x^2)``` we would like to find degree=1, right?
 | 3. may want to have a rational power operator such that doing ```pow(x^3,4/3)``` will give us ```x^4``` (i.e. polynomial in x of degree 4). 
 | 4. may want to have a log operator.
trig.cpp | 1. may want to add secant, cosecant, and cotangent operators, and their inverse operators (arc-). However, these are not strictly necessary since they can be defined through sine, cosine and tangent using reciprocal (1/sin, 1/cosine, etc) (do you think a reciprocal operator may be useful?). It would be nice for the user to have them predefined though. Same thing for hyperbolic functions (sinh, cosh, tanh, asinh,...,sech,...,asech,etc). These should probably go in arithmetic.cpp though.
fundamentals.cpp | 1. we may want to change the name of this file to fundamentals_test.cpp for consistency with other test files
mpfr_complex.hpp | 1.  when defining "Some static functions which construct special numbers" the comments of several of them read "Construct the number 0" instead of the appropriate comment (see 1,2 and -1)
 | 2. when defining operator+ the comments (in all three cases) read "multiplication" instead of "addition"

**Comment by ofloveandhate** [comment]
Thanks for the further comments.  

I have the following replies:
1. Regarding arithmetic.cpp, number 2, 3, these kinds of simplifications might cause issues further down the line.  sqrt(x^2) is not x, but rather the absolute value of x -- so doing these simplifications might cause incorrect symbolic problems.
2. i don't think i want to add any further trig nodes right now, until there is a need looming.  bertini1 has been fine without, and YAGNI dictates i not implement them now.

Other than these two points, I will make all the changes you list.  Thanks!

**Comment by ofloveandhate** [comment]
I've been thinking about the x^3/x^-1 thing, too.  it discards a singularity at 0...  so i think this may not be desirable.  we should leave it to the user to decide they want to eliminate singularities, not assume they want it eliminated.  anyone have any feedback regarding this?

**Comment by fpancald** [comment]
I agree with your reply on arithmetic.cpp (2,3), and the fact that the extra operations I suggested are not strictly necessary, since they can be defined with the operation already existent. 
However, we may want to have in our guide a section explaining how to add custom made operations such as those. Because if a user is using them all the time they may not want to type the all thing from the basic operations.

For the polynomial quotients that simplify  to a polynomial, we should probably have an option that the user can turn ON and OFF to ignore these singularities, but the default setting should probably be OFF (i.e. DO count those as singular expressions).

**Comment by ofloveandhate** [comment]
sounds like a good compromise.  i will add the switch for that behavior
later, when we actually need it.  again, YAGNI dictates that this
modification wait.  if someone ends up needing the switch for
simplification, we will add it.

**Comment by fpancald** [comment]
Yes that is what I meant. For now it's OK as it is.
Let me know when you have all the code updated. I will then make a final pull and compile, to make sure everything works, and then I will send my report to Dan.

**Comment by ofloveandhate** [comment]
@fpancald @jbcolli2 I made all changes requested of me.  In addition, I improved the generated html documentation, and revised the README.md for the main page, and the GitHub face of b2.

As you review the changes I made, consider building the documentation in the b2/code/doc folder, and seeing if it is up to snuff.  I expect there are many things we want to improve about the documentation, especially example usage code and a more casual english summary of the code, but I think that should wait for a subsequent pull request.  I think we can easily do this in parallel to other improvements once we get a bit further along with tracking, which is coming along nicely.

I believe this is ready to pull.  I did end up causing several conflicts due to moving some code around, so now whoever resolves the pull request will need to resolve those conflicts.  I think the blanket resolution in this case is to just take my files.  Let me know if help is needed in resolving them, or consider granting me write access to the bertiniteam/b2 repo so I can do it myself.

-daniel brake

**Comment by fpancald** [comment]
Was able to compile code, run tests and generate documentation successfully after pulling the last changes.
I finished my report and sent it to Dan Bates. @bertiniteam

**Pull request merged**
