### PR TITLE
Python bindings for bertini2 currently in main repo

### PR DESCRIPTION
**Pull request by jbcolli2**
This pull request contains code to expose the bertini2 code to python.  The bertini code that has been exposed includes

- All multiprecision data types
- Dynamically allocated Eigen vectors and matrices for `dbl` and `mpfr` data types
- All node objects
- System objects and all StartSystem objects, including TotalDegree
- A parser for parsing an input file into a system

To install:

- Go to the python folder
- autoreconf -vfi
- ./configure
- make install
This will create a python module called `libpybertini` which can be imported to python code.

In python/test there are python unit tests giving an example of how to use the majority of the code.

Please review this request and feel free to contact me with changes and improvements you find.

### CODE REVIEW

**Comment by aliddell** [comment]
I'm looking at class DiffTest in differentiation_test.py in the `setUp` function. In it you `set_current_value` for every `Variable` twice -- once as a Python `complex`, the next as an `mpfr_complex`. What is the intent behind this? Does `set_current_value` hold multiple types of value (`float`, `mpfr_t`, `mpq_t`) depending on context? Because when I comment out lines 22-27 and run the tests, nothing happens. But when I comment out lines 11,13,15,17-19, `test_power_rule` fails with 

`Traceback (most recent call last):
  File "/home/alan/working_copies/b2/python/test/differentiation_test.py", line 65, in test_power_rule
    self.assertLessEqual(np.abs(df.evald(x).real / (-4.86)-1), tol_d)
AssertionError: 1.0 not less than or equal to 1e-14`

and `test_prod_rule` and `test_transcendental` fail with similar errors.

**Comment by jbcolli2** [comment]
set_current_value sets the value of the Variable.  Each Variable can hold
values of multiple data types, either fixed precision complex doubles or
mpfr complex types.  The idea being that we can add data types as we expand
Bertini.   By calling set_current_value twice I set both the fixed
precision and mpfr data types in each Variable node.

   If you don't call set_current_value, I believe the values of the
Variables should just be set to zero, which would explain the errors.
Though there should also be errors when you comment out lines 22-27, as the
mpfr tests should also fail.  And in fact when I comment out lines 22-27 on
my local repo, I get three errors that look like

Traceback (most recent call last):

  File
"/Users/jcollins/Documents/West_Texas/Research/Bertini/JebsFork_b2/python/test/differentiation_test.py",
line 68, in test_power_rule

    self.assertLessEqual(abs(df.evalmp(x).real / mpfr_float("-4.86")-1),
tol_mp)

AssertionError: nan not less than or equal to
1.00000000000000000000000000000010e-27

On Wed, Mar 23, 2016 at 3:47 PM, Alan Liddell <notifications@github.com>
wrote:

> I'm looking at class DiffTest in differentiation_test.py in the setUp
> function. In it you set_current_value for every Variable twice -- once as
> a Python complex, the next as an mpfr_complex. What is the intent behind
> this? Does set_current_value hold multiple types of value (float, mpfr_t,
> mpq_t) depending on context? Because when I comment out lines 22-27 and
> run the tests, nothing happens. But when I comment out lines
> 11,13,15,17-19, test_power_rule fails with
>
> Traceback (most recent call last):
> File "/home/alan/working_copies/b2/python/test/differentiation_test.py",
> line 65, in test_power_rule
> self.assertLessEqual(np.abs(df.evald(x).real / (-4.86)-1), tol_d)
> AssertionError: 1.0 not less than or equal to 1e-14
>
> and test_prod_rule and test_transcendental fail with similar errors.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bertiniteam/b2/pull/25#issuecomment-200538010>
>



-- 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by aliddell** [comment]
Yes, these are the errors I'm getting. In light of this, all the other tests look pretty solid. After someone takes a look at the C++ code (not my forte), I say accept this pull request.

**Comment by ofloveandhate** [comment]
Looking at a list of source files, the branch is nice and clean.  no extra files, no temp files.

**Comment by ofloveandhate** [comment]
one thing that isn't working for me (and i knew about it), is calling "import libpybertini" in ipython from any directory.  right now, i have to call it from .libs/ in the b2/python directory, which is weird.  

what i'd like to happen is to make install libpybertini from source, then be able to import it from anywhere.  i will look up how to get the library to install to the correct location...  my sys.path has first in its listing /usr/local/bin, which seems reasonable.  but libpybertini is built as a library, and hence installed to /usr/local/lib, so python doesn't find it when i import.  

can others confirm?

**Comment by aliddell** [comment]
@ofloveandhate that's correct. If you `import sys` and look at `sys.path`, it should present you with a list of search directories where it can import from. One option to consider is to `make install` to a standard folder in this path (a subdirectory of /usr/lib/python2.x, maybe). For testing, I've just done `import sys; sys.path.insert(0, dirname)` where `dirname` is a string containing a path to the .libs folder. This inserts that folder at the very top of your search hierarchy, so if it encounters a libpybertini (or any other named module) there, it will ignore one found in a later directory.

**Comment by jbcolli2** [comment]
Dan,
   So let me make sure I got this right.  Are you saying that you can't
call import libpybertini from ipython except when you are in a particular
directory?

On Thu, Mar 31, 2016 at 10:56 AM, Alan Liddell <notifications@github.com>
wrote:

> @ofloveandhate <https://github.com/ofloveandhate> that's correct. If you import
> sys and look at sys.path, it should present you with a list of search
> directories where it can import from. One option to consider is to make
> install to a standard folder in this path (a subdirectory of
> /usr/lib/python2.x, maybe). For testing, I've just done import sys;
> sys.path.insert(0, dirname) where dirname is a string containing a path
> to the .libs folder. This inserts that folder at the very top of your
> search hierarchy, so if it encounters a libpybertini (or any other named
> module) there, it will ignore one found in a later directory.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bertiniteam/b2/pull/25#issuecomment-203998681>
>



-- 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by ofloveandhate** [comment]
no, not really.  rather, i have to specify a path to the library.  have you
somehow got it rigged so that you can be at $HOME, enter ipython, and
import libpybertini, without any additional information or configuration to
your python env?

**Comment by ofloveandhate** [comment]
i feel like there are two options for resolving this problem.

1. continue to install to `/usr/local/lib` by default, and encourage users to modify their search path IN python, or
2. consider switching build tools to the one provided for building boost.python libraries, bjam.  autotools are not recommended for building boost.python libraries, yet this is what we are doing, so perhaps switching to `bjam` would solve this problem for us.

i've struggled to get a vanilla run of `./configure make make install` to install to a directory other than `/usr/local/lib`.  i got the `lib` prefix to vanish, and got rid of the version number, so now it just is named `pybertini.so`, as desired, but i haven't been able to get there with installing to `/usr/local/bin`, which is on the python search path by default.  i've not yet given up, but am certainly thinking that using bjam might be the way to go.  i just hesitate to learn another build system...  

any thoughts?

**Comment by aliddell** [comment]
If we don't want to switch to bjam, we might consider a [post-install hook](http://www.gnu.org/software/automake/manual/automake.html#Extending) to make a symlink to a Python lib directory. (Found [here](https://lists.gnu.org/archive/html/automake/2009-05/msg00115.html), where the guy is doing something similar.)

I'll go on record though and say that this is probably too convoluted and brittle and if bjam can make this simpler, why not give it a try.

**Comment by jbcolli2** [comment]
So the answer to your question Dan is yes I can build anywhere, but I
just realized that I changed the search path for python in my .profile.  I
had forgotten I'd even put it there, and I'm sure I did it to solve this
exact problem while I was testing.

  I think the symlink idea might work.  Isn't that essentially what brew
does with all their installs? It seems this might be better, especially if
the alternative is switching all our builds to using bjam.  Or were we
thinking about just using bjam for the python build?

On Thu, Mar 31, 2016 at 12:14 PM, Alan Liddell <notifications@github.com>
wrote:

> If we don't want to switch to bjam, we might consider a post-install hook
> <http://www.gnu.org/software/automake/manual/automake.html#Extending> to
> make a symlink to a Python lib directory. (Found here
> <https://lists.gnu.org/archive/html/automake/2009-05/msg00115.html>,
> where the guy is doing something similar.)
>
> I'll go on record though and say that this is probably too convoluted and
> brittle and if bjam can make this simpler, why not give it a try.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bertiniteam/b2/pull/25#issuecomment-204028548>
>



-- 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by ofloveandhate** [comment]
regarding bjam, we can switch the entire project, or just the python part.
 i already want to also provide a cmake build option for the core (i've
recently used cmake, and it wasn't too bad).  so maybe adding bjam is not
so bad?

for now, let's just do a hook, and let it stand until we get a better idea
of what is more correct, and easier on users.  i've used hooks before, with
bertini1.  it's pretty easy.  it is, however, a little brittle, and
probably not windows friendly with VS.

**Comment by ofloveandhate** [comment]
ok, y'all,
i was able to write an install hook, and corresponding uninstall hook, for the library.  i was also able to remove lib and version number from the name of the library.  whether this will work on windows remains to be seen.  @jbcolli2 i will do a PR into your dev folder once i get this cleaned up.  the only impact it should have is on b2/python/src/Makemodule.am, and in the tests, where the import statements will need to be modified.

before I make this change, can we confirm the final name of the library?  is pybertini good?  i didn't like the lib in front, which is why i removed it.

**Comment by ofloveandhate** [comment]
I've read the code in the pull request.  It's good code.  Spartan on commenting in C++, but fairly readable.  

The only things it really is missing are docstrings.  Very little exposed functionality comes with python docstrings, and we should decide how to provide these.  It would be great if the docstrings could be auto-generated from the C++ documentation, where appropriate.  But in some places, the python docstrings will necessarily have to be different from the C++, so this is not a two-birds-one-stone solution, sadly.

Should we accept in the absence of the in-python documentation?  As we move forward, the interface is bound to change at least some, so the docs will have to change, too.  So I'm open to accepting this without documentation at this time, so long as the documentation gets written about the same time as the core stabilizes.  @jbcolli2 @aliddell  what do you think?

**Comment by aliddell** [comment]
Yeah, I'm fine with that.

**Comment by jbcolli2** [comment]
That sounds good to me.

On Thu, Mar 31, 2016 at 2:39 PM, Alan Liddell <notifications@github.com>
wrote:

> Yeah, I'm fine with that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bertiniteam/b2/pull/25#issuecomment-204094163>
>



-- 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by ofloveandhate** [comment]
I finally got the python thing figured out.  there's a canonical way, built in!  no hooks necessary!

**Comment by aliddell** [comment]
Would that be [pythondir/pyexecdir/pkgpyexecdir](https://www.gnu.org/software/automake/manual/html_node/Python.html)?

**Comment by ofloveandhate** [comment]
pyexecdir, though autoconf manages it for us, so the particular variable is
not explicitly used.

**Comment by ofloveandhate** [comment]
alan, will you confirm that pybertini installs correctly on your machine, and that you can import it in both python and ipython with no additional modifications beyond vanilla python install?  once we confirm that, i think we should accept this PR.

**Comment by aliddell** [comment]
Can confirm that pybertini installs correctly:

> Libraries have been installed in:
>    /usr/local/lib/python2.7/dist-packages
> 
and

> mekagojira:python (1019)% ipython  
> Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 2.3.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> These commands were executed:
> >>> from __future__ import division, print_function
> >>> import numpy as np
> >>> import scipy as sp
> >>> import matplotlib.pyplot as plt
> 
> In [1]: import pybertini
> 
> In [2]: dir(pybertini)
> Out[2]: 
> ['ArcCosOperator',
>  'ArcSinOperator',
>  'ArcTanOperator',
>  'BinaryOperator',
>  'CosOperator',
>  'Differential',
>  'E',
>  'ExpOperator',
>  'Float',
>  'Function',
>  'Integer',
>  'IntegerPowerOperator',
>  'Jacobian',
>  'ListFunction',
>  'ListInt',
>  'ListJacobian',
>  'ListRational',
>  'ListVariableGroup',
>  'LogOperator',
>  'MatrixXd',
>  'MatrixXmp',
>  'MultOperator',
>  'NamedSymbol',
>  'NaryOperator',
>  'NegateOperator',
>  'Node',
>  'Number',
>  'Operator',
>  'Pi',
>  'PowerOperator',
>  'Rational',
>  'SinOperator',
>  'SqrtOperator',
>  'StartSystem',
>  'SumOperator',
>  'Symbol',
>  'System',
>  'TanOperator',
>  'TotalDegree',
>  'TrigOperator',
>  'UnaryOperator',
>  'Variable',
>  'VariableGroup',
>  'VectorXd',
>  'VectorXmp',
>  '__doc__',
>  '__file__',
>  '__name__',
>  '__package__',
>  'abs',
>  'abs2',
>  'acos',
>  'acosh',
>  'arg',
>  'asin',
>  'asinh',
>  'atan',
>  'atanh',
>  'conj',
>  'cos',
>  'cosh',
>  'cube',
>  'default_precision',
>  'exp',
>  'imag',
>  'inverse',
>  'log',
>  'make_e',
>  'make_i',
>  'make_pi',
>  'mpfr_complex',
>  'mpfr_float',
>  'mpfr_int',
>  'mpfr_rational',
>  'norm',
>  'parse_system',
>  'polar',
>  'real',
>  'sin',
>  'sinh',
>  'sqrt',
>  'square',
>  'tan',
>  'tanh']

Python3 doesn't find it, as we expected.

**Comment by bertiniteam** [comment]
acting as bertiniteam, i am accepting this pull request, considering review over and satisfactory.

**Comment by bertiniteam** [comment]
this pull request has been resolved.  i recommend all coders pull into your own repo from bertiniteam/b2/master to pick up the changes.

**Pull request merged**
