### PR TITLE
Hotfix/redo iadd and isub operators

### PR DESCRIPTION
**Pull request by jbcolli2**
A small change was made to the += and -= operators when used on a SumOperator node.  There was an inconsistency between how += and -= were implemented and how *= and /= were implemented for MultOperator nodes.  This inconsistency was fixed.

### CODE REVIEW

**Comment by ofloveandhate** [comment]
I do wonder why this pull request has so many commits?  I think that we need to learn how to make the pull request reflect only the changes actually made since the most recent code in bertiniteam/.  It feels like the commits above replay many of the changes already accepted in the official codebase.  Does anybody know why?

**Comment by jbcolli2** [comment]
This could be my fault.  This was my first pull request that I initiated
and I wasn't entirely sure how to do it.  I may have put too much in the
pull request because I didn't know how to cut it down to just the important
commits.

Jeb

On Tue, Nov 24, 2015 at 2:07 PM, daniel brake <notifications@github.com>
wrote:

> I do wonder why this pull request has so many commits? I think that we
> need to learn how to make the pull request reflect only the changes
> actually made since the most recent code in bertiniteam/. It feels like the
> commits above replay many of the changes already accepted in the official
> codebase. Does anybody know why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bertiniteam/b2/pull/15#issuecomment-159390207>.
>



-- 

J.B. Collins, Ph.D
West Texas A&M University
Department of Mathematics
CC 421D
806-651-5260

**Comment by ofloveandhate** [comment]
I think that if you fetch-and-merge from bertiniteam, you should become up to date, and hopefully all those commits should go away.  if not, then you may need to re-check out the bertiniteam/b2/develop branch, and re-do your changes, then do a fresh pull request.

**Comment by ofloveandhate** [comment]
this pull request targets the wrong branch of bertiniteam.  we should pull into develop, not master.

**Comment by jbcolli2** [comment]
Even for hotfixes?  My understanding was that hotfixes were the only changes, aside from release branches, that could be pulled directly into the master, since they are by definition small changes.

**Comment by ofloveandhate** [comment]
ok, it's a hot fix.  we haven't talked about a policy for hot fixes.  does
anyone have any input?

if all pull requests go into develop, the pattern is something like:


                                    /---> allotherusers/master/etc
jbcolli2/branchforanyPR --> bertiniteam/develop --> bertiniteam/master

\--> bertiniteam/release/current_release

jeb is proposing for hotfixes:

jbcolli2/hotfix/bla --> bertiniteam/master --> bertiniteam/develop -->
bertiniteam/release/current_release
                                                                \--->
allotherusers/master/etc

any preferences or opinions?

daniel

**Comment by jbcolli2** [comment]
For a more visual model of what I'm proposing, see http://nvie.com/posts/a-successful-git-branching-model/

I think the basic question is: are we making a quick fix to the final release version, or is this simply a small update to the develop branch.  I guess a hotfix could be either, depending on what is being fixed.

**Comment by matthewniemerg** [comment]
I like the design of that model that Jeb posted, and I must say that the flow chart looks good.

**Comment by aliddell** [comment]
Yes, I think this is a good design.

**Comment by bertiniteam** [comment]
due to the messy beginning stages of development and re-written history, which is the source of the duplicate commits, i am closing this pull request until the repo gets cleaned up.

**Pull request closed without merging**
